package grpcstarter.example.entity;

import jakarta.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pet
 */
public class Pet {
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.id")
    private Integer id;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.name")
    private String name;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.status")
    private Status status;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.id")
    public Integer getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.name")
    public String getName() {
        return name;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.status")
    public Status getStatus() {
        return status;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: pet.status")
    public void setStatus(Status status) {
        this.status = status;
    }
}
