grpc:
  server:
    debug:
      enabled: true
    exception-handling:
      use-default: true
  client:
    channels:
      - authority: localhost:${grpc.server.port:9090}
        metadata:
          - key: foo
            values: [ bar, bar, foo ]
        stubs:
          - com.freemanan.foo.v1.api.FooServiceGrpc.FooServiceBlockingStub
          - com.freemanan.foo.v1.api.FooServiceGrpc.FooServiceStub