grpc:
  server:
    debug:
      enabled: true
  client:
    channels:
      - authority: localhost:${grpc.server.port:9090}
        stubs:
          - com.freemanan.foo.v1.api.FooServiceGrpc.FooServiceBlockingStub
          - com.freemanan.foo.v1.api.FooServiceGrpc.FooServiceStub
