grpc:
  server:
    reflection:
      enabled: true
  client:
    shutdown-timeout: 1000
    channels:
      - authority: localhost:${grpc.server.port:9090}
        classes:
          - foo.FooServiceGrpc.FooServiceBlockingStub
        stubs:
          - io.grpc.**.Health*Stub
        services:
          - grpc.reflection.*.ServerReflection
          - grpc.testing.SimpleService
