# SSL Bundle configuration using JKS format
# This example shows how to use JKS keystores and truststores

spring:
  ssl:
    bundle:
      jks:
        server-bundle:
          keystore:
            location: "classpath:server.p12"
            password: "server-password"
            type: "PKCS12"
        client-bundle:
          truststore:
            location: "classpath:ca.p12"
            password: "ca-password"
            type: "PKCS12"

grpc:
  server:
    reflection:
      enabled: true
    ssl-bundle: server-bundle
  client:
    authority: localhost:${grpc.server.port:9090}
    ssl-bundle: client-bundle
