# Legacy TLS configuration (deprecated since 3.5.0)
# This configuration is still supported but will show deprecation warnings
# Please migrate to SSL Bundle configuration in application.yaml

grpc:
  server:
    reflection:
      enabled: true
    tls:
      key-manager:
        cert-chain: classpath:server.crt
        private-key: classpath:server.key
  client:
    authority: localhost:${grpc.server.port:9090}
    tls:
      trust-manager:
        root-certs: classpath:ca.crt
